import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  UserHeader from './ui/UserHeader';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <UserHeader/>
      {/* TODO: insert header with links to sign up / sign in / sign out depending on session */}
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
